// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using TunisianArabic.Models;

namespace TunisianArabic.Migrations
{
    [DbContext(typeof(WordContext))]
    [Migration("20171121225635_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TunisianArabic.Models.Word", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ArabWord");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<string>("EngWord")
                        .IsRequired();

                    b.Property<string>("FbTypping");

                    b.Property<string>("Nature")
                        .IsRequired();

                    b.Property<string>("PicURL");

                    b.Property<string>("Pronunciation");

                    b.Property<int>("Score");

                    b.Property<string>("TunWord")
                        .IsRequired();

                    b.HasKey("ID");

                    b.ToTable("Word");
                });
#pragma warning restore 612, 618
        }
    }
}
